### ISSUE TITLE
Modify build scripts to update the default version of template validator image.

### ISSUE THREAD

**Issue by akrejcir** [kubevirt/ssp-operator#178]
It would be convenient, if the build process updates the default template validator image version in the file [internal/operands/template-validator/defaults.go](https://github.com/kubevirt/ssp-operator/blob/v0.11.1/internal/operands/template-validator/defaults.go#L4)

It should be equal to the env variable [`VALIDATOR_IMG`](https://github.com/kubevirt/ssp-operator/blob/v0.11.1/Makefile#L25).

/kind enhancement

**Environment**:
- SSP Operator version: `v0.11.1`

**Comment by vatsalparekh** [comment]
I think it can be easily done in github actions

**Comment by akrejcir** [comment]
I think it would be better to do it in `Makefile`. It would be useful for development, that I could just write:
```
make build-template-validator-container push-template-validator-container
make container-build container-push
make deploy
```
And it would deploy latest ssp with the latest template validator.

**Comment by akrejcir** [comment]
Currently, it also works, but with the "hack" that we define the value of env variable in the deployment manifest:
https://github.com/kubevirt/ssp-operator/blob/v0.11.1/config/manager/manager.template.yaml#L33
