### ISSUE TITLE
`pull-ci-kubevirt-ssp-operator-master-e2e-upgrade-functests`  failing to lookup previous release version from GitHub API

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/ssp-operator#499]
/kind bug

**What happened**:

`pull-ci-kubevirt-ssp-operator-master-e2e-upgrade-functests` is failing due to a failed attempt to lookup the last released version of the operator:

https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-kubevirt-ssp-operator-master-e2e-upgrade-functests

```
error: unable to read URL "https://github.com/kubevirt/ssp-operator/releases/download/null/ssp-operator.yaml", server reported 404 Not Found, status code=404
```
https://github.com/kubevirt/ssp-operator/blob/98598bd3c6e85ff0d0b5f6525bfe8d6614a56381/automation/e2e-upgrade-functests/run.sh#L29-L35

```
$ RELEASE_BRANCH=$(curl 'https://api.github.com/repos/kubevirt/ssp-operator/branches' |
    jq '[.[].name | select(startswith("release-v"))] | max_by(ltrimstr("release-v") | split(".") | map(tonumber))' |
    tr -d '"')
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3090  100  3090    0     0  42270      0 --:--:-- --:--:-- --:--:-- 42328
$ echo $RELEASE_BRANCH
release-v0.17
$ curl 'https://api.github.com/repos/kubevirt/ssp-operator/releases' |
  jq --arg BRANCH "${RELEASE_BRANCH}" '[.[] | select(.target_commitish == $BRANCH) | .name] | .[0]' |
  tr -d '"'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  225k    0  225k    0     0   396k      0 --:--:-- --:--:-- --:--:--  396k
null
```

**What you expected to happen**:

Lookup is successful and the job continues.

**How to reproduce it**:

Run `pull-ci-kubevirt-ssp-operator-master-e2e-upgrade-functests` .

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- SSP Operator version:
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by akrejcir** [comment]
This is caused because I've created `release-v0.17`, branch, but no release yet. I will look into it.

**Comment by lyarwood** [comment]
Can we remove the branch for now?

**Comment by akrejcir** [comment]
Yes, let's do that. The main reason why I created the branch was to unblock PRs. But now it's decided that the blocked PRs go to `v0.17.0` anyway, so they can be merged to master.

**Comment by akrejcir** [comment]
Done
