### ISSUE TITLE
Add vm-console-proxy

### ISSUE THREAD

**Issue by codingben** [kubevirt/ssp-operator#502]
Deploy vm-console-proxy using ssp-operator.

- https://github.com/kubevirt/ssp-operator/pull/491
- https://github.com/kubevirt/ssp-operator/pull/498
- https://github.com/kubevirt/ssp-operator/pull/501
- https://github.com/kubevirt/ssp-operator/pull/509
- https://github.com/kubevirt/ssp-operator/pull/515

**Comment by akrejcir** [comment]
https://github.com/kubevirt/ssp-operator/pull/507

**Comment by codingben** [comment]
https://github.com/kubevirt/ssp-operator/pull/510

**Comment by codingben** [comment]
https://github.com/kubevirt/ssp-operator/pull/509

**Comment by codingben** [comment]
@dominikholler @akrejcir Can we close it? If not, is there any reason to keep it?

**Comment by akrejcir** [comment]
Yes, you can close this.
