### ISSUE TITLE
Use example CR provided by kubevirt

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/ssp-operator#517]
/kind enhancement

**What happened**:

The CI tests use a hardcoded kubevirt CR with some additional required feature flags added.

It would be nice if the test were using the example CR provided with the latest kubevirt release and were patching in any missing required feature flags instead of using a hardcoded kubevirt CR.

This will help to avoid situations like https://github.com/kubevirt/ssp-operator/pull/516, where deprecated values in the CR cause issues.

See:
- https://github.com/kubevirt/ssp-operator/blob/19e5c5ebbab29861556d54c5407bcc62e199957a/automation/common/deploy-kubevirt-and-cdi.sh#L18
- https://github.com/kubevirt/kubevirt/releases/download/v0.59.0/kubevirt-cr.yaml

**Comment by akrejcir** [comment]
The PR was merged.
