### ISSUE TITLE
windows-customize-configmaps: Change name of ipv4 subinterface for kubernetes

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/ssp-operator#539]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

The change in https://github.com/kubevirt/tekton-tasks-operator/pull/142 should be applied to the kubernetes version of `windows-customize-configmaps.yaml` after https://github.com/kubevirt/ssp-operator/pull/532 is merged.

**Comment by codingben** [comment]
It's already applied in this PR [1].

[1] https://github.com/kubevirt/ssp-operator/compare/146cfedde84992173570d11c276bb32e7c083cc7..3fe065d06eeb408dc5cd8fee1bd6b2daadd24632

**Comment by 0xFelix** [comment]
I would strongly prefer to keep this out of PR #532. The PR is already very large and this fix can easily be applied in a follow up. #532 should apply just the minimal changes to import the tekton tasks into SSP.

**Comment by codingben** [comment]
Then let's apply that fix in tekton-tasks-operator and leave it copied in this PR. This way it makes me think that #532 will add issue that can be solved now.

**Comment by codingben** [comment]
What I'm trying to say is that issues should be opened after #532 is merged, and not before. Until then, they can be kept in tekton-tasks-operator repository.

**Comment by 0xFelix** [comment]
Tbh I don't see any harm in opening the issue here already. We don't want to make any more changes to TTO afterall.
