### ISSUE TITLE
Operator crashes when kubevirt is not installed

### ISSUE THREAD

**Issue by akrejcir** [kubevirt/ssp-operator#682]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
If `ssp-operator` deployment is created on a cluster without kubevirt CRDs, it will crash and cause `CrashLoopBackoff` state.

This can happen when `ssp-operator` is installed using OLM.

**Comment by codingben** [comment]
We'll need to check which operand is using KubeVirt CRD and stop reconciliation of it? like we do in Tekton operands, if Tekton CRD doesn't exist.

**Comment by akrejcir** [comment]
It is probably caused by the new controller that watches VMs, introduced in: https://github.com/kubevirt/ssp-operator/pull/663

**Comment by 0xFelix** [comment]
Pinging @machadovilaca, can you PTAL?

**Comment by akrejcir** [comment]
I did not realize it during the review. But this is not an urgent bug. I've opened this issue so that we don't forget about it.

**Comment by machadovilaca** [comment]
Looking
