### ISSUE TITLE
 kubevirt.io/v1alpha3 is now deprecated

### ISSUE THREAD

**Issue by dominikholler** [kubevirt/ssp-operator#716]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

create-vm and wait-for-wmi-status log
```
W1030 15:05:30.309784      17 warnings.go:70] kubevirt.io/v1alpha3 is now deprecated and will be removed in a future release.
```

**What you expected to happen**:

no warning

**How to reproduce it**:
run  windows-efi-installer pipeline

**Anything else we need to know?**:

**Environment**:
OpenShift Virtualization 4.14.0

**Comment by akrejcir** [comment]
The pipelines are no longer in SSP operator.

/close
